# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb51d0a58023a9609901719cb19f5fb176cbd359349d7c4c62c77f17ef2cc9dc62ec1185d326a1ceead0286203eb16b27441e8583b81a4f6a60bf3fda7dc17f

test:
  secret_key_base: 256b6fdfeef1b979ea37fd2a8ae8bde644a145d36d3544ac408ba2a97a967167d53dded26595663c826ac68ea971ddb34898145e7275a4b5d1bcc41fba0d1321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
